name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-test-discovery --enable-code-coverage
    - name: swift-codecov
      uses: mattpolzin/swift-codecov-action@0.3.0
